---
title: "narrniche statistical analysis"
output: html_document
date: "2025-12-16"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(lme4)
library(lmerTest)
library(report)
```

```{r}
data <- read_csv("../data/processed/data.csv")
data <- drop_na(data)
data
```

## Count Model

```{r}
cm_else <- lmer(lf_count_log ~ else_freq_log + (1|lang) + (1|field), data)
summary(cm_else)

cm_narr <- lmer(lf_count_log ~ narr_freq_log + (1|lang) + (1|field), data)
summary(cm_narr)

cm_narrelse <- lmer(lf_count_log ~ narr_freq_log + else_freq_log + (1|lang) + (1|field), data)
summary(cm_narrelse)

anova(cm_else, cm_narr, cm_narrelse)
```


## Entropy Model

```{r}
em_else <- lmer(lf_entropy ~ else_freq_log + (1|lang) + (1|field), data)
summary(em_else)

em_narr <- lmer(lf_entropy ~ narr_freq_log + (1|lang) + (1|field), data)
summary(em_narr)

em_narrelse <- lmer(lf_entropy ~ narr_freq_log + else_freq_log + (1|lang) + (1|field), data)
summary(em_narrelse)

anova(em_else, em_narr, em_narrelse)
```

```{r}
data$pred_count_narr <- predict(cm_narr)
data$pred_count_else <- predict(cm_else)
data$pred_entropy_narr <- predict(em_narr)
data$pred_entropy_else <- predict(em_else)
write_csv(data, '../data/processed/data_pred.csv')
```



```{r}

slope_A = 1.356e-01
slope_B = 6.530e-02
se_A = 9.540e-03
se_B = 8.200e-03
n = 3243

# Calculate Welch's T-test statistic
t_stat <- (slope_A - slope_B) / sqrt(se_A^2 + se_B^2)

# Degrees of freedom
df <- ((se_A^2 + se_B^2)^2) / (((se_A^2)^2 / (n - 2)) + ((se_B^2)^2 / (n - 2)))

# Calculate p-value
p_value <- 2 * pt(-abs(t_stat), df)

# Display the test statistic and p-value
t_stat
p_value
```


```{r}
slope_A = 1.568e-02
slope_B = -9.903e-03
se_A = 1.337e-02
se_B = 1.163e-02
n = 3243

# Calculate Welch's T-test statistic
t_stat <- (slope_A - slope_B) / sqrt(se_A^2 + se_B^2)

# Degrees of freedom
df <- ((se_A^2 + se_B^2)^2) / (((se_A^2)^2 / (n - 2)) + ((se_B^2)^2 / (n - 2)))

# Calculate p-value
p_value <- 2 * pt(-abs(t_stat), df)

# Display the test statistic and p-value
t_stat
p_value
```
